apiVersion: v1
kind: Service
metadata:
  name: shop-two-db
  labels:
    app: shop-two
spec:
  ports:
    - port: 3306
  selector:
    app: shop-two
    tier: sp-two-db-mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-shop-two
  labels:
    app: shop-two
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-two-db
  labels:
    app: shop-two
spec:
  selector:
    matchLabels:
      app: shop-two
      tier: sp-two-db-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shop-two
        tier: sp-two-db-mysql
    spec:
      containers:
        - image: mysql:5.6
          name: sp-two-db-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass-two
                  key: password
          ports:
            - containerPort: 3306
              name: sp-two-db-mysql
          volumeMounts:
            - name: mysql-persistent-storage-shop-two
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage-shop-two
          persistentVolumeClaim:
            claimName: mysql-pv-claim-shop-two
